name: Github action secret

on:
  push:
    branches: [ "main" ]
  
jobs:
  secret-in-github-actions:
      runs-on: ubuntu-latest

    steps:
      - name: 1. Echo out Github Action Secrets to the logs
        uses: |
          echo "The Gihub Secret Action will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to open Github Actions Secret: "
          echo ${{ secrets.SECRET_TOKEN }} | sed 's/./& /g'
