name: Github action secret

on:
  push:
    branches: [ "main" ]
  
jobs:
  secret-in-github-actions:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Echo out Github Action Secrets to the logs
        run: |
          echo "The Gihub Secret Action will be masked: "
          echo ${{ secrets.SECRET_TOKEN }}
          echo "Trick to open Github Actions Secret: "
          echo ${{ secrets.SECRET_TOKEN }} | sed 's/./& /g'
          
      - name: 2. Github Action if statement (true)
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST == 'Trust-1'
        run: echo "I know what the secret token is!"
        
      - name: 3. Conditional Github Action (false)
        shell: bash
        env:
          WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
        if: env.WHO_TO_TRUST != 'Trust-one'
        run: echo "I was wrong thinking github that the secret is 'Trust-one'!"
